#!/usr/bin/env python

## chapter 8

# raise Exception('hyperdrive overload')

import exceptions
print dir(exceptions)


~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"chapter8.py" 10L, 121C                                       10,0-1        All
