#!/usr/bin/env python
#String Lists
#Ask the user for a string and print out whether this string is a palindrome or not.

wrd = input(" please enter a string here : ")
wrd = str(wrd)
rvs = wrd[::-1]
print (rvs)

if wrd == rvs:
    print ("This word is a palindrome")

else:
    print ("This word is not a palindrome")
