#!/usr/bin/env python
number = int(input("please enter a integer number here: "))

divisors = range(1, number +1 )

list = []

for i in divisors:
    if number % i == 0:
        list.append(i)
        
print (list)
